//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class Rotator : MonoBehaviour
{
	public float rotateSpeed;

	public Rotator ()
	{

	}

	void FixedUpdate() {
		transform.Rotate (Vector3.back * rotateSpeed);
	}
}
